change name of input argument from fasta to input
this should cause it to print the intended error message rather than the rather confusing "AttributeError: 'Namespace' object has no attribute 'fasta'"